export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_PROFILEPIC = 'UPDATE_PROFILEPIC';
export const VIEW_RECO = 'VIEW_RECO';
export const VIEW_ITIN = 'VIEW_ITIN';
